name: Deploy to EC2

on:
  push:
    branches:
      - abc  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 18.118.32.46 >> ~/.ssh/known_hosts  # Replace with your actual EC2 public IP

      - name: Deploy to EC2
        run: |
          # First, sync to a temporary directory
          rsync -avz --delete ./ ubuntu@18.118.32.46:/tmp/website
          # Then, copy to the final location using sudo
          ssh ubuntu@18.118.32.46 "sudo rsync -avz --delete /tmp/website/ /var/www/html/"
